services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    container_name: ${KEYCLOAK_CONTAINER_NAME}
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${KEYCLOAK_DATABASE_CONTAINER_NAME}:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USERNAME}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8088
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: debug
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    command: start-dev --features organization --import-realm
    volumes:
      - ./dev/keycloak/import:/opt/keycloak/data/import
    depends_on:
      - keycloak-db
    ports:
      - "8088:8080"

  keycloak-db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${KEYCLOAK_DATABASE_CONTAINER_NAME}
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  platform-db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${PLATFORM_DATABASE_CONTAINER_NAME}
    environment:
      POSTGRES_DB: platform
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  pulsar-standalone:
    image: apachepulsar/pulsar:${PULSAR_VERSION}
    container_name: ${PULSAR_CONTAINER_NAME}
    command: bin/pulsar standalone
    user: root
    volumes:
      - pulsar-data:/pulsar/data
      - pulsar-config:/pulsar/conf
    ports:
      - "18080:8080"
      - "6650:6650"

  pulsar-manager:
    image: apachepulsar/pulsar-manager:${PULSAR_MANAGER_VERSION}
    container_name: ${PULSAR_MANAGER_CONTAINER_NAME}
    environment:
      - SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties
    ports:
      - "9527:9527"
      - "7750:7750"

volumes:
  pulsar-data:
    name: pulsar-data
  pulsar-config:
    name: pulsar-config