keycloak:
  url: 'http://localhost:8088'
  realm: 'master'
  admin:
    realm: 'master'
    grant-type: 'password'
    client-id: 'admin-cli'
    client-secret: ''
    username: 'admin'
    password: ''
---
spring.datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
---
spring.pulsar:
  client:
    service-url: pulsar://localhost:6650
  admin:
    service-url: http://localhost:18080
---
spring.application.name: rize-platform
spring.threads.virtual.enabled: true
spring.modulith.events.jdbc.schema-initialization.enabled: true
---
spring.docker.compose:
  enabled: true
  file: docker-compose.yaml
  lifecycle-management: start_only
---
logging.level:
    org.springframework: WARN
    org.atmosphere: ERROR
    org.apache: WARN
    com.vaadin: WARN
    com.zaxxer: WARN