keycloak:
  url: 'http://localhost:8088'
  realm: 'master'
  admin:
    realm: 'master'
    grant-type: 'password'
    client-id: 'admin-cli'
    client-secret: ''
    username: 'admin'
    password: ''
---
logging:
  level:
    org.springframework: WARN
    org.atmosphere: ERROR
    org.apache: WARN
    com.vaadin: WARN
---
spring:
  threads:
    virtual:
      enabled: true
---
spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
      lifecycle-management: start_only