access-manager:
  clients:
    application-gateway:
      redirect-uri-pattern: 'https://%{alias}%.rize-os.dev'
---
keycloak:
  url: http://localhost:8080
  realm: rize-os
  admin:
    realm: master
    grant-type: password
    client-id: admin-cli
    username: _keycloak-admin
    password: secret
---
datasource:
  url: jdbc:postgresql://localhost:5432/access_manager
  username: _postgres-admin
  password: secret
---
logging:
  level:
    rize.os: DEBUG