access-manager:
  clients:
    application-gateway:
      redirect-uri-pattern: 'http://localhost:8080/%{alias}%'
---
keycloak:
  url: http://localhost:8080
  realm: master
  admin:
    realm: master
    grant-type: password
    client-id: admin-cli
    client-secret: '-'
    username: admin
    password: '-'
---
spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: org.postgresql.Driver
---
server:
  port: ${access-manager.port:9090}
---
spring:
  modulith:
    republish-outstanding-events-on-restart: true
    events:
      jdbc:
        schema-initialization:
          enabled: true
---
spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
      lifecycle-management: start_only
