application-gateway:
  security:
    oauth2:
      issuer-uri: http://localhost:8080/realms/rize-os
      client-id: application-gateway-org-rize-os
      client-secret: tWg1E8DTMIBRoMdosztNQsaMBx0qNN28
---
application-gateway:
  server:
    base-path: /rize-os