name: rize.os build

on:
  create:
    tags:
      - '*'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RIZE_COCKPIT_IMAGE: 'rizeos/rize-cockpit'
      DOCKER_IO_USERNAME: ${{ secrets.DOCKER_IO_USERNAME }}
      DOCKER_IO_PASSWORD: ${{ secrets.DOCKER_IO_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml', '**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.11'

      - name: Run Maven package
        run: mvn package -Pproduction -Dmaven.test.skip=true

      - name: Get rize.os version
        id: rize_version
        run: echo "RIZE_VERSION=$(mvn help:evaluate -Dexpression=rize.os.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_IO_USERNAME }}
          password: ${{ env.DOCKER_IO_PASSWORD }}

      - name: Build and push rize.cockpit Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.RIZE_COCKPIT_IMAGE }}:${{ env.RIZE_VERSION }}
