name: commons-publish

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      MAVEN_CLI_OPTS: --batch-mode --errors --fail-at-end

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Publish to GitHub Packages
        run: mvn --projects commons $MAVEN_CLI_OPTS deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}